// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebRtcData.proto

package io.forsta.librelay.webrtc;

public final class WebRtcDataProtos {
  private WebRtcDataProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ConnectedOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint64 id = 1;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint64 id = 1;</code>
     */
    long getId();
  }
  /**
   * Protobuf type {@code signal.Connected}
   */
  public static final class Connected extends
      com.google.protobuf.GeneratedMessage
      implements ConnectedOrBuilder {
    // Use Connected.newBuilder() to construct.
    private Connected(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Connected(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Connected defaultInstance;
    public static Connected getDefaultInstance() {
      return defaultInstance;
    }

    public Connected getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Connected(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WebRtcDataProtos.internal_static_signal_Connected_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WebRtcDataProtos.internal_static_signal_Connected_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WebRtcDataProtos.Connected.class, WebRtcDataProtos.Connected.Builder.class);
    }

    public static com.google.protobuf.Parser<Connected> PARSER =
        new com.google.protobuf.AbstractParser<Connected>() {
      public Connected parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Connected(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Connected> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    private void initFields() {
      id_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static WebRtcDataProtos.Connected parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WebRtcDataProtos.Connected parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WebRtcDataProtos.Connected parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WebRtcDataProtos.Connected parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WebRtcDataProtos.Connected parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WebRtcDataProtos.Connected parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static WebRtcDataProtos.Connected parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static WebRtcDataProtos.Connected parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static WebRtcDataProtos.Connected parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WebRtcDataProtos.Connected parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(WebRtcDataProtos.Connected prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signal.Connected}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements WebRtcDataProtos.ConnectedOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WebRtcDataProtos.internal_static_signal_Connected_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WebRtcDataProtos.internal_static_signal_Connected_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WebRtcDataProtos.Connected.class, WebRtcDataProtos.Connected.Builder.class);
      }

      // Construct using io.forsta.librelay.webrtc.WebRtcDataProtos.Connected.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WebRtcDataProtos.internal_static_signal_Connected_descriptor;
      }

      public WebRtcDataProtos.Connected getDefaultInstanceForType() {
        return WebRtcDataProtos.Connected.getDefaultInstance();
      }

      public WebRtcDataProtos.Connected build() {
        WebRtcDataProtos.Connected result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public WebRtcDataProtos.Connected buildPartial() {
        WebRtcDataProtos.Connected result = new WebRtcDataProtos.Connected(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WebRtcDataProtos.Connected) {
          return mergeFrom((WebRtcDataProtos.Connected)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WebRtcDataProtos.Connected other) {
        if (other == WebRtcDataProtos.Connected.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        WebRtcDataProtos.Connected parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (WebRtcDataProtos.Connected) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint64 id = 1;
      private long id_ ;
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:signal.Connected)
    }

    static {
      defaultInstance = new Connected(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:signal.Connected)
  }

  public interface HangupOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint64 id = 1;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint64 id = 1;</code>
     */
    long getId();
  }
  /**
   * Protobuf type {@code signal.Hangup}
   */
  public static final class Hangup extends
      com.google.protobuf.GeneratedMessage
      implements HangupOrBuilder {
    // Use Hangup.newBuilder() to construct.
    private Hangup(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Hangup(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Hangup defaultInstance;
    public static Hangup getDefaultInstance() {
      return defaultInstance;
    }

    public Hangup getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Hangup(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WebRtcDataProtos.internal_static_signal_Hangup_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WebRtcDataProtos.internal_static_signal_Hangup_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WebRtcDataProtos.Hangup.class, WebRtcDataProtos.Hangup.Builder.class);
    }

    public static com.google.protobuf.Parser<Hangup> PARSER =
        new com.google.protobuf.AbstractParser<Hangup>() {
      public Hangup parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Hangup(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Hangup> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    private void initFields() {
      id_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static WebRtcDataProtos.Hangup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WebRtcDataProtos.Hangup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WebRtcDataProtos.Hangup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WebRtcDataProtos.Hangup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WebRtcDataProtos.Hangup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WebRtcDataProtos.Hangup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static WebRtcDataProtos.Hangup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static WebRtcDataProtos.Hangup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static WebRtcDataProtos.Hangup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WebRtcDataProtos.Hangup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(WebRtcDataProtos.Hangup prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signal.Hangup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements WebRtcDataProtos.HangupOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WebRtcDataProtos.internal_static_signal_Hangup_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WebRtcDataProtos.internal_static_signal_Hangup_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WebRtcDataProtos.Hangup.class, WebRtcDataProtos.Hangup.Builder.class);
      }

      // Construct using io.forsta.librelay.webrtc.WebRtcDataProtos.Hangup.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WebRtcDataProtos.internal_static_signal_Hangup_descriptor;
      }

      public WebRtcDataProtos.Hangup getDefaultInstanceForType() {
        return WebRtcDataProtos.Hangup.getDefaultInstance();
      }

      public WebRtcDataProtos.Hangup build() {
        WebRtcDataProtos.Hangup result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public WebRtcDataProtos.Hangup buildPartial() {
        WebRtcDataProtos.Hangup result = new WebRtcDataProtos.Hangup(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WebRtcDataProtos.Hangup) {
          return mergeFrom((WebRtcDataProtos.Hangup)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WebRtcDataProtos.Hangup other) {
        if (other == WebRtcDataProtos.Hangup.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        WebRtcDataProtos.Hangup parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (WebRtcDataProtos.Hangup) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint64 id = 1;
      private long id_ ;
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:signal.Hangup)
    }

    static {
      defaultInstance = new Hangup(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:signal.Hangup)
  }

  public interface VideoStreamingStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional uint64 id = 1;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint64 id = 1;</code>
     */
    long getId();

    // optional bool enabled = 2;
    /**
     * <code>optional bool enabled = 2;</code>
     */
    boolean hasEnabled();
    /**
     * <code>optional bool enabled = 2;</code>
     */
    boolean getEnabled();
  }
  /**
   * Protobuf type {@code signal.VideoStreamingStatus}
   */
  public static final class VideoStreamingStatus extends
      com.google.protobuf.GeneratedMessage
      implements VideoStreamingStatusOrBuilder {
    // Use VideoStreamingStatus.newBuilder() to construct.
    private VideoStreamingStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private VideoStreamingStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final VideoStreamingStatus defaultInstance;
    public static VideoStreamingStatus getDefaultInstance() {
      return defaultInstance;
    }

    public VideoStreamingStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private VideoStreamingStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              enabled_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WebRtcDataProtos.internal_static_signal_VideoStreamingStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WebRtcDataProtos.internal_static_signal_VideoStreamingStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WebRtcDataProtos.VideoStreamingStatus.class, WebRtcDataProtos.VideoStreamingStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<VideoStreamingStatus> PARSER =
        new com.google.protobuf.AbstractParser<VideoStreamingStatus>() {
      public VideoStreamingStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VideoStreamingStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<VideoStreamingStatus> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional uint64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional uint64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    // optional bool enabled = 2;
    public static final int ENABLED_FIELD_NUMBER = 2;
    private boolean enabled_;
    /**
     * <code>optional bool enabled = 2;</code>
     */
    public boolean hasEnabled() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bool enabled = 2;</code>
     */
    public boolean getEnabled() {
      return enabled_;
    }

    private void initFields() {
      id_ = 0L;
      enabled_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, enabled_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, enabled_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static WebRtcDataProtos.VideoStreamingStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WebRtcDataProtos.VideoStreamingStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WebRtcDataProtos.VideoStreamingStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WebRtcDataProtos.VideoStreamingStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WebRtcDataProtos.VideoStreamingStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WebRtcDataProtos.VideoStreamingStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static WebRtcDataProtos.VideoStreamingStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static WebRtcDataProtos.VideoStreamingStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static WebRtcDataProtos.VideoStreamingStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WebRtcDataProtos.VideoStreamingStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(WebRtcDataProtos.VideoStreamingStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signal.VideoStreamingStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements WebRtcDataProtos.VideoStreamingStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WebRtcDataProtos.internal_static_signal_VideoStreamingStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WebRtcDataProtos.internal_static_signal_VideoStreamingStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WebRtcDataProtos.VideoStreamingStatus.class, WebRtcDataProtos.VideoStreamingStatus.Builder.class);
      }

      // Construct using io.forsta.librelay.webrtc.WebRtcDataProtos.VideoStreamingStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        enabled_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WebRtcDataProtos.internal_static_signal_VideoStreamingStatus_descriptor;
      }

      public WebRtcDataProtos.VideoStreamingStatus getDefaultInstanceForType() {
        return WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance();
      }

      public WebRtcDataProtos.VideoStreamingStatus build() {
        WebRtcDataProtos.VideoStreamingStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public WebRtcDataProtos.VideoStreamingStatus buildPartial() {
        WebRtcDataProtos.VideoStreamingStatus result = new WebRtcDataProtos.VideoStreamingStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.enabled_ = enabled_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WebRtcDataProtos.VideoStreamingStatus) {
          return mergeFrom((WebRtcDataProtos.VideoStreamingStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WebRtcDataProtos.VideoStreamingStatus other) {
        if (other == WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEnabled()) {
          setEnabled(other.getEnabled());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        WebRtcDataProtos.VideoStreamingStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (WebRtcDataProtos.VideoStreamingStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional uint64 id = 1;
      private long id_ ;
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      // optional bool enabled = 2;
      private boolean enabled_ ;
      /**
       * <code>optional bool enabled = 2;</code>
       */
      public boolean hasEnabled() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bool enabled = 2;</code>
       */
      public boolean getEnabled() {
        return enabled_;
      }
      /**
       * <code>optional bool enabled = 2;</code>
       */
      public Builder setEnabled(boolean value) {
        bitField0_ |= 0x00000002;
        enabled_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool enabled = 2;</code>
       */
      public Builder clearEnabled() {
        bitField0_ = (bitField0_ & ~0x00000002);
        enabled_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:signal.VideoStreamingStatus)
    }

    static {
      defaultInstance = new VideoStreamingStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:signal.VideoStreamingStatus)
  }

  public interface DataOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .signal.Connected connected = 1;
    /**
     * <code>optional .signal.Connected connected = 1;</code>
     */
    boolean hasConnected();
    /**
     * <code>optional .signal.Connected connected = 1;</code>
     */
    WebRtcDataProtos.Connected getConnected();
    /**
     * <code>optional .signal.Connected connected = 1;</code>
     */
    WebRtcDataProtos.ConnectedOrBuilder getConnectedOrBuilder();

    // optional .signal.Hangup hangup = 2;
    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     */
    boolean hasHangup();
    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     */
    WebRtcDataProtos.Hangup getHangup();
    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     */
    WebRtcDataProtos.HangupOrBuilder getHangupOrBuilder();

    // optional .signal.VideoStreamingStatus videoStreamingStatus = 3;
    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     */
    boolean hasVideoStreamingStatus();
    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     */
    WebRtcDataProtos.VideoStreamingStatus getVideoStreamingStatus();
    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     */
    WebRtcDataProtos.VideoStreamingStatusOrBuilder getVideoStreamingStatusOrBuilder();
  }
  /**
   * Protobuf type {@code signal.Data}
   */
  public static final class Data extends
      com.google.protobuf.GeneratedMessage
      implements DataOrBuilder {
    // Use Data.newBuilder() to construct.
    private Data(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Data(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Data defaultInstance;
    public static Data getDefaultInstance() {
      return defaultInstance;
    }

    public Data getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Data(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              WebRtcDataProtos.Connected.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = connected_.toBuilder();
              }
              connected_ = input.readMessage(WebRtcDataProtos.Connected.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(connected_);
                connected_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              WebRtcDataProtos.Hangup.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = hangup_.toBuilder();
              }
              hangup_ = input.readMessage(WebRtcDataProtos.Hangup.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(hangup_);
                hangup_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              WebRtcDataProtos.VideoStreamingStatus.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = videoStreamingStatus_.toBuilder();
              }
              videoStreamingStatus_ = input.readMessage(WebRtcDataProtos.VideoStreamingStatus.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(videoStreamingStatus_);
                videoStreamingStatus_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WebRtcDataProtos.internal_static_signal_Data_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WebRtcDataProtos.internal_static_signal_Data_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WebRtcDataProtos.Data.class, WebRtcDataProtos.Data.Builder.class);
    }

    public static com.google.protobuf.Parser<Data> PARSER =
        new com.google.protobuf.AbstractParser<Data>() {
      public Data parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Data(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Data> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .signal.Connected connected = 1;
    public static final int CONNECTED_FIELD_NUMBER = 1;
    private WebRtcDataProtos.Connected connected_;
    /**
     * <code>optional .signal.Connected connected = 1;</code>
     */
    public boolean hasConnected() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .signal.Connected connected = 1;</code>
     */
    public WebRtcDataProtos.Connected getConnected() {
      return connected_;
    }
    /**
     * <code>optional .signal.Connected connected = 1;</code>
     */
    public WebRtcDataProtos.ConnectedOrBuilder getConnectedOrBuilder() {
      return connected_;
    }

    // optional .signal.Hangup hangup = 2;
    public static final int HANGUP_FIELD_NUMBER = 2;
    private WebRtcDataProtos.Hangup hangup_;
    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     */
    public boolean hasHangup() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     */
    public WebRtcDataProtos.Hangup getHangup() {
      return hangup_;
    }
    /**
     * <code>optional .signal.Hangup hangup = 2;</code>
     */
    public WebRtcDataProtos.HangupOrBuilder getHangupOrBuilder() {
      return hangup_;
    }

    // optional .signal.VideoStreamingStatus videoStreamingStatus = 3;
    public static final int VIDEOSTREAMINGSTATUS_FIELD_NUMBER = 3;
    private WebRtcDataProtos.VideoStreamingStatus videoStreamingStatus_;
    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     */
    public boolean hasVideoStreamingStatus() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     */
    public WebRtcDataProtos.VideoStreamingStatus getVideoStreamingStatus() {
      return videoStreamingStatus_;
    }
    /**
     * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
     */
    public WebRtcDataProtos.VideoStreamingStatusOrBuilder getVideoStreamingStatusOrBuilder() {
      return videoStreamingStatus_;
    }

    private void initFields() {
      connected_ = WebRtcDataProtos.Connected.getDefaultInstance();
      hangup_ = WebRtcDataProtos.Hangup.getDefaultInstance();
      videoStreamingStatus_ = WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, connected_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, hangup_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, videoStreamingStatus_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, connected_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, hangup_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, videoStreamingStatus_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static WebRtcDataProtos.Data parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WebRtcDataProtos.Data parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WebRtcDataProtos.Data parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WebRtcDataProtos.Data parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WebRtcDataProtos.Data parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WebRtcDataProtos.Data parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static WebRtcDataProtos.Data parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static WebRtcDataProtos.Data parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static WebRtcDataProtos.Data parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static WebRtcDataProtos.Data parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(WebRtcDataProtos.Data prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code signal.Data}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements WebRtcDataProtos.DataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WebRtcDataProtos.internal_static_signal_Data_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WebRtcDataProtos.internal_static_signal_Data_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WebRtcDataProtos.Data.class, WebRtcDataProtos.Data.Builder.class);
      }

      // Construct using io.forsta.librelay.webrtc.WebRtcDataProtos.Data.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getConnectedFieldBuilder();
          getHangupFieldBuilder();
          getVideoStreamingStatusFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (connectedBuilder_ == null) {
          connected_ = WebRtcDataProtos.Connected.getDefaultInstance();
        } else {
          connectedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (hangupBuilder_ == null) {
          hangup_ = WebRtcDataProtos.Hangup.getDefaultInstance();
        } else {
          hangupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (videoStreamingStatusBuilder_ == null) {
          videoStreamingStatus_ = WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance();
        } else {
          videoStreamingStatusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WebRtcDataProtos.internal_static_signal_Data_descriptor;
      }

      public WebRtcDataProtos.Data getDefaultInstanceForType() {
        return WebRtcDataProtos.Data.getDefaultInstance();
      }

      public WebRtcDataProtos.Data build() {
        WebRtcDataProtos.Data result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public WebRtcDataProtos.Data buildPartial() {
        WebRtcDataProtos.Data result = new WebRtcDataProtos.Data(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (connectedBuilder_ == null) {
          result.connected_ = connected_;
        } else {
          result.connected_ = connectedBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (hangupBuilder_ == null) {
          result.hangup_ = hangup_;
        } else {
          result.hangup_ = hangupBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (videoStreamingStatusBuilder_ == null) {
          result.videoStreamingStatus_ = videoStreamingStatus_;
        } else {
          result.videoStreamingStatus_ = videoStreamingStatusBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WebRtcDataProtos.Data) {
          return mergeFrom((WebRtcDataProtos.Data)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WebRtcDataProtos.Data other) {
        if (other == WebRtcDataProtos.Data.getDefaultInstance()) return this;
        if (other.hasConnected()) {
          mergeConnected(other.getConnected());
        }
        if (other.hasHangup()) {
          mergeHangup(other.getHangup());
        }
        if (other.hasVideoStreamingStatus()) {
          mergeVideoStreamingStatus(other.getVideoStreamingStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        WebRtcDataProtos.Data parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (WebRtcDataProtos.Data) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .signal.Connected connected = 1;
      private WebRtcDataProtos.Connected connected_ = WebRtcDataProtos.Connected.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          WebRtcDataProtos.Connected, WebRtcDataProtos.Connected.Builder, WebRtcDataProtos.ConnectedOrBuilder> connectedBuilder_;
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public boolean hasConnected() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public WebRtcDataProtos.Connected getConnected() {
        if (connectedBuilder_ == null) {
          return connected_;
        } else {
          return connectedBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public Builder setConnected(WebRtcDataProtos.Connected value) {
        if (connectedBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          connected_ = value;
          onChanged();
        } else {
          connectedBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public Builder setConnected(
          WebRtcDataProtos.Connected.Builder builderForValue) {
        if (connectedBuilder_ == null) {
          connected_ = builderForValue.build();
          onChanged();
        } else {
          connectedBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public Builder mergeConnected(WebRtcDataProtos.Connected value) {
        if (connectedBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              connected_ != WebRtcDataProtos.Connected.getDefaultInstance()) {
            connected_ =
              WebRtcDataProtos.Connected.newBuilder(connected_).mergeFrom(value).buildPartial();
          } else {
            connected_ = value;
          }
          onChanged();
        } else {
          connectedBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public Builder clearConnected() {
        if (connectedBuilder_ == null) {
          connected_ = WebRtcDataProtos.Connected.getDefaultInstance();
          onChanged();
        } else {
          connectedBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public WebRtcDataProtos.Connected.Builder getConnectedBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getConnectedFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      public WebRtcDataProtos.ConnectedOrBuilder getConnectedOrBuilder() {
        if (connectedBuilder_ != null) {
          return connectedBuilder_.getMessageOrBuilder();
        } else {
          return connected_;
        }
      }
      /**
       * <code>optional .signal.Connected connected = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          WebRtcDataProtos.Connected, WebRtcDataProtos.Connected.Builder, WebRtcDataProtos.ConnectedOrBuilder>
          getConnectedFieldBuilder() {
        if (connectedBuilder_ == null) {
          connectedBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              WebRtcDataProtos.Connected, WebRtcDataProtos.Connected.Builder, WebRtcDataProtos.ConnectedOrBuilder>(
                  connected_,
                  getParentForChildren(),
                  isClean());
          connected_ = null;
        }
        return connectedBuilder_;
      }

      // optional .signal.Hangup hangup = 2;
      private WebRtcDataProtos.Hangup hangup_ = WebRtcDataProtos.Hangup.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          WebRtcDataProtos.Hangup, WebRtcDataProtos.Hangup.Builder, WebRtcDataProtos.HangupOrBuilder> hangupBuilder_;
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public boolean hasHangup() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public WebRtcDataProtos.Hangup getHangup() {
        if (hangupBuilder_ == null) {
          return hangup_;
        } else {
          return hangupBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public Builder setHangup(WebRtcDataProtos.Hangup value) {
        if (hangupBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          hangup_ = value;
          onChanged();
        } else {
          hangupBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public Builder setHangup(
          WebRtcDataProtos.Hangup.Builder builderForValue) {
        if (hangupBuilder_ == null) {
          hangup_ = builderForValue.build();
          onChanged();
        } else {
          hangupBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public Builder mergeHangup(WebRtcDataProtos.Hangup value) {
        if (hangupBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              hangup_ != WebRtcDataProtos.Hangup.getDefaultInstance()) {
            hangup_ =
              WebRtcDataProtos.Hangup.newBuilder(hangup_).mergeFrom(value).buildPartial();
          } else {
            hangup_ = value;
          }
          onChanged();
        } else {
          hangupBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public Builder clearHangup() {
        if (hangupBuilder_ == null) {
          hangup_ = WebRtcDataProtos.Hangup.getDefaultInstance();
          onChanged();
        } else {
          hangupBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public WebRtcDataProtos.Hangup.Builder getHangupBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getHangupFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      public WebRtcDataProtos.HangupOrBuilder getHangupOrBuilder() {
        if (hangupBuilder_ != null) {
          return hangupBuilder_.getMessageOrBuilder();
        } else {
          return hangup_;
        }
      }
      /**
       * <code>optional .signal.Hangup hangup = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          WebRtcDataProtos.Hangup, WebRtcDataProtos.Hangup.Builder, WebRtcDataProtos.HangupOrBuilder>
          getHangupFieldBuilder() {
        if (hangupBuilder_ == null) {
          hangupBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              WebRtcDataProtos.Hangup, WebRtcDataProtos.Hangup.Builder, WebRtcDataProtos.HangupOrBuilder>(
                  hangup_,
                  getParentForChildren(),
                  isClean());
          hangup_ = null;
        }
        return hangupBuilder_;
      }

      // optional .signal.VideoStreamingStatus videoStreamingStatus = 3;
      private WebRtcDataProtos.VideoStreamingStatus videoStreamingStatus_ = WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          WebRtcDataProtos.VideoStreamingStatus, WebRtcDataProtos.VideoStreamingStatus.Builder, WebRtcDataProtos.VideoStreamingStatusOrBuilder> videoStreamingStatusBuilder_;
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public boolean hasVideoStreamingStatus() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public WebRtcDataProtos.VideoStreamingStatus getVideoStreamingStatus() {
        if (videoStreamingStatusBuilder_ == null) {
          return videoStreamingStatus_;
        } else {
          return videoStreamingStatusBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public Builder setVideoStreamingStatus(WebRtcDataProtos.VideoStreamingStatus value) {
        if (videoStreamingStatusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          videoStreamingStatus_ = value;
          onChanged();
        } else {
          videoStreamingStatusBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public Builder setVideoStreamingStatus(
          WebRtcDataProtos.VideoStreamingStatus.Builder builderForValue) {
        if (videoStreamingStatusBuilder_ == null) {
          videoStreamingStatus_ = builderForValue.build();
          onChanged();
        } else {
          videoStreamingStatusBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public Builder mergeVideoStreamingStatus(WebRtcDataProtos.VideoStreamingStatus value) {
        if (videoStreamingStatusBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              videoStreamingStatus_ != WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance()) {
            videoStreamingStatus_ =
              WebRtcDataProtos.VideoStreamingStatus.newBuilder(videoStreamingStatus_).mergeFrom(value).buildPartial();
          } else {
            videoStreamingStatus_ = value;
          }
          onChanged();
        } else {
          videoStreamingStatusBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public Builder clearVideoStreamingStatus() {
        if (videoStreamingStatusBuilder_ == null) {
          videoStreamingStatus_ = WebRtcDataProtos.VideoStreamingStatus.getDefaultInstance();
          onChanged();
        } else {
          videoStreamingStatusBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public WebRtcDataProtos.VideoStreamingStatus.Builder getVideoStreamingStatusBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getVideoStreamingStatusFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      public WebRtcDataProtos.VideoStreamingStatusOrBuilder getVideoStreamingStatusOrBuilder() {
        if (videoStreamingStatusBuilder_ != null) {
          return videoStreamingStatusBuilder_.getMessageOrBuilder();
        } else {
          return videoStreamingStatus_;
        }
      }
      /**
       * <code>optional .signal.VideoStreamingStatus videoStreamingStatus = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          WebRtcDataProtos.VideoStreamingStatus, WebRtcDataProtos.VideoStreamingStatus.Builder, WebRtcDataProtos.VideoStreamingStatusOrBuilder>
          getVideoStreamingStatusFieldBuilder() {
        if (videoStreamingStatusBuilder_ == null) {
          videoStreamingStatusBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              WebRtcDataProtos.VideoStreamingStatus, WebRtcDataProtos.VideoStreamingStatus.Builder, WebRtcDataProtos.VideoStreamingStatusOrBuilder>(
                  videoStreamingStatus_,
                  getParentForChildren(),
                  isClean());
          videoStreamingStatus_ = null;
        }
        return videoStreamingStatusBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:signal.Data)
    }

    static {
      defaultInstance = new Data(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:signal.Data)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_Connected_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_signal_Connected_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_Hangup_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_signal_Hangup_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_VideoStreamingStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_signal_VideoStreamingStatus_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_signal_Data_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_signal_Data_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020WebRtcData.proto\022\006signal\"\027\n\tConnected\022" +
      "\n\n\002id\030\001 \001(\004\"\024\n\006Hangup\022\n\n\002id\030\001 \001(\004\"3\n\024Vid" +
      "eoStreamingStatus\022\n\n\002id\030\001 \001(\004\022\017\n\007enabled" +
      "\030\002 \001(\010\"\210\001\n\004Data\022$\n\tconnected\030\001 \001(\0132\021.sig" +
      "nal.Connected\022\036\n\006hangup\030\002 \001(\0132\016.signal.H" +
      "angup\022:\n\024videoStreamingStatus\030\003 \001(\0132\034.si" +
      "gnal.VideoStreamingStatusB5\n!org.thought" +
      "crime.securesms.webrtcB\020WebRtcDataProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_signal_Connected_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_signal_Connected_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_signal_Connected_descriptor,
              new java.lang.String[] { "Id", });
          internal_static_signal_Hangup_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_signal_Hangup_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_signal_Hangup_descriptor,
              new java.lang.String[] { "Id", });
          internal_static_signal_VideoStreamingStatus_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_signal_VideoStreamingStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_signal_VideoStreamingStatus_descriptor,
              new java.lang.String[] { "Id", "Enabled", });
          internal_static_signal_Data_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_signal_Data_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_signal_Data_descriptor,
              new java.lang.String[] { "Connected", "Hangup", "VideoStreamingStatus", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
